### ISSUE TITLE
What does (400, 1024) feature mean?

### ISSUE THREAD

**Issue by smygw72** [hazeld/rank-aware-attention-network#2]
We have features from I3D as input to Rank-aware Attention Network. Each feature is composed of two dimensions of (400, 1024). 

I wonder what does each feature mean? 
(Maybe, the first dimension is corresponds to randomly selected frame and the second is something feature from somewhere layer in I3D. So, I think features no longer include spatial information.)

**Comment by hazeld** [comment]
Hi,

The second dimension, 1024 is the size of the feature extracted from I3D before the last fully connected layer. The first dimension, 400 is the number these features extracted at different temporal points in a video. So we uniformly sample 400 video snippets temporally, and for each snippet we get a 1024d feature.

You're correct that the features no longer contain spatial information. 

If you're wanting to extract features yourself which contain spatial information and can't because some of the videos have been taken off YouTube, email me and I can help you with the missing videos.

Best,
Hazel

**Comment by smygw72** [comment]
Thank you for answering my questions. As you pointed that I'm trying to extract spatial information.
I appreciate your offer and I'm going to email you to get some missing videos.

Sincerely,
smygw72
